main: com.tibthink.payRespect.Main
name: F
version: 1.1.4
author: tibthink
description: Sends a F to the chat whenever someone dies

commands:
   Test: 
      description: Tests to make sure the plugin works